# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9ea4cefb08713df266ab843dcea325317d5fff223059a21a7c5dae97e97ab64814dbf765da7fad44d35517331902c3648e8aa05e3cf459c705a27fb13a88129

test:
  secret_key_base: e46518056a59ec045c0bc7286b98cfb5b6c1847c54088c2c52cbf22c5e78c6d82aaa061356123e9f3ef191e9c885e739b98671b6a46435b7e3657c6761b91fe3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
